name: Build and run Sitecore CLI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Install and run Sitecore CLI
        run: |
          cd ../../..
          dotnet new tool-manifest
          dotnet nuget add source -n Sitecore https://sitecore.myget.org/F/sc-packages/api/v3/index.json
          dotnet tool install Sitecore.CLI

      - name: Sitecore CLI Show Version
        run: |
          dotnet sitecore init
          ch-cli --version
