name: Build and run Sitecore CLI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Install Content Hub CLI
        run: |
          brew tap sitecore/content-hub
          brew install ch-cli
          ch-cli --version

      - name: CLI PoC
        run: | 
          ch-cli endpoint add --name test2 --url https://base-dam-asof20230330.sitecoresandbox.cloud --client-id 
CLI2 --client-secret 123
          ch-cli endpoint list


          